name: Update BDD.js

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Version increment (patch, minor, major)'
        required: true
        default: 'patch'

jobs:
  update-bdd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update BDD.js version
        run: |
          node -e "
          const fs = require('fs');
          const file = 'BDD.js';
          const content = fs.readFileSync(file, 'utf-8');
          const match = content.match(/window\.dbVersion\s*=\s*['\"](\d+)\.(\d+)\.(\d+)['\"]/);
          if(match){
            let [_, major, minor, patch] = match.map(Number);
            switch('${{ github.event.inputs.increment }}'){
              case 'major': major++; minor=0; patch=0; break;
              case 'minor': minor++; patch=0; break;
              default: patch++;
            }
            const newContent = content.replace(/window\.dbVersion\s*=\s*['\"]\d+\.\d+\.\d+['\"]/, `window.dbVersion='${major}.${minor}.${patch}'`);
            fs.writeFileSync(file, newContent, 'utf-8');
            console.log('BDD.js version updated to', `${major}.${minor}.${patch}`);
          } else {
            console.error('Version not found in BDD.js');
            process.exit(1);
          }
          "

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add BDD.js
          git commit -m "Update BDD.js version [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
